/**
* XRF OAuth2 Token Introspection Request API
* XRF OAuth2 Authorization server, token introspection API 
*
* The version of the OpenAPI document: 1
* Contact: tolgaoa@vt.edu
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "TokenIntrospectionRequestApiImpl.h"

namespace xrf {
namespace api {

using namespace xrf::model;

TokenIntrospectionRequestApiImpl::TokenIntrospectionRequestApiImpl(const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : TokenIntrospectionRequestApi(rtr)
{
}

void TokenIntrospectionRequestApiImpl::token_intro_request(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter &response){
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

}
}

