/**
* XRFc Service test API
* XRFc service testing API 
*
* The version of the OpenAPI document: 1
* Contact: tolgaoa@vt.edu
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "ServTestErr.h"
#include "Helpers.h"

#include <sstream>

namespace xrf::model
{

ServTestErr::ServTestErr()
{
    m_Error = "";
    m_Error_description = "";
    m_Error_descriptionIsSet = false;
    m_Error_uri = "";
    m_Error_uriIsSet = false;
    
}

void ServTestErr::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw xrf::helpers::ValidationException(msg.str());
    }
}

bool ServTestErr::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool ServTestErr::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "ServTestErr" : pathPrefix;

                
    return success;
}

bool ServTestErr::operator==(const ServTestErr& rhs) const
{
    return
    
    
    (getError() == rhs.getError())
     &&
    
    
    ((!errorDescriptionIsSet() && !rhs.errorDescriptionIsSet()) || (errorDescriptionIsSet() && rhs.errorDescriptionIsSet() && getErrorDescription() == rhs.getErrorDescription())) &&
    
    
    ((!errorUriIsSet() && !rhs.errorUriIsSet()) || (errorUriIsSet() && rhs.errorUriIsSet() && getErrorUri() == rhs.getErrorUri()))
    
    ;
}

bool ServTestErr::operator!=(const ServTestErr& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const ServTestErr& o)
{
    j = nlohmann::json();
    j["error"] = o.m_Error;
    if(o.errorDescriptionIsSet())
        j["error_description"] = o.m_Error_description;
    if(o.errorUriIsSet())
        j["error_uri"] = o.m_Error_uri;
    
}

void from_json(const nlohmann::json& j, ServTestErr& o)
{
    j.at("error").get_to(o.m_Error);
    if(j.find("error_description") != j.end())
    {
        j.at("error_description").get_to(o.m_Error_description);
        o.m_Error_descriptionIsSet = true;
    } 
    if(j.find("error_uri") != j.end())
    {
        j.at("error_uri").get_to(o.m_Error_uri);
        o.m_Error_uriIsSet = true;
    } 
    
}

std::string ServTestErr::getError() const
{
    return m_Error;
}
void ServTestErr::setError(std::string const& value)
{
    m_Error = value;
}
std::string ServTestErr::getErrorDescription() const
{
    return m_Error_description;
}
void ServTestErr::setErrorDescription(std::string const& value)
{
    m_Error_description = value;
    m_Error_descriptionIsSet = true;
}
bool ServTestErr::errorDescriptionIsSet() const
{
    return m_Error_descriptionIsSet;
}
void ServTestErr::unsetError_description()
{
    m_Error_descriptionIsSet = false;
}
std::string ServTestErr::getErrorUri() const
{
    return m_Error_uri;
}
void ServTestErr::setErrorUri(std::string const& value)
{
    m_Error_uri = value;
    m_Error_uriIsSet = true;
}
bool ServTestErr::errorUriIsSet() const
{
    return m_Error_uriIsSet;
}
void ServTestErr::unsetError_uri()
{
    m_Error_uriIsSet = false;
}


} // namespace xrf::model

