/**
* XRFc Service test API
* XRFc service testing API 
*
* The version of the OpenAPI document: 1
* Contact: tolgaoa@vt.edu
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ServTestReq.h
 *
 * Contains information related to the service test request
 */

#ifndef ServTestReq_H_
#define ServTestReq_H_


#include <string>
#include <nlohmann/json.hpp>

namespace xrf::model
{

/// <summary>
/// Contains information related to the service test request
/// </summary>
class  ServTestReq
{
public:
    ServTestReq();
    virtual ~ServTestReq() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const ServTestReq& rhs) const;
    bool operator!=(const ServTestReq& rhs) const;

    /////////////////////////////////////////////
    /// ServTestReq members

    /// <summary>
    /// 
    /// </summary>
    std::string getCertificate() const;
    void setCertificate(std::string const& value);
    bool certificateIsSet() const;
    void unsetCertificate();

    friend void to_json(nlohmann::json& j, const ServTestReq& o);
    friend void from_json(const nlohmann::json& j, ServTestReq& o);
protected:
    std::string m_Certificate;
    bool m_CertificateIsSet;
    
};

} // namespace xrf::model

#endif /* ServTestReq_H_ */
