/**
* NRF NFManagement Service
* NRF NFManagement Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.2.0-alpha.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * AccessType.h
 *
 * Indicates wether the access is  via 3GPP or via non-3GPP.
 */

#ifndef AccessType_H_
#define AccessType_H_


#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// Indicates wether the access is  via 3GPP or via non-3GPP.
/// </summary>
class  AccessType
{
public:
    AccessType();
    virtual ~AccessType() = default;

    enum class eAccessType {
    // To have a valid default value.
    // Avoiding name clashes with user defined
    // enum values
    INVALID_VALUE_OPENAPI_GENERATED = 0,
    _3GPP_ACCESS, 
    NON_3GPP_ACCESS
    };

    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const AccessType& rhs) const;
    bool operator!=(const AccessType& rhs) const;

    /////////////////////////////////////////////
    /// AccessType members

    AccessType::eAccessType getValue() const;
    void setValue(AccessType::eAccessType value);
    
    friend void to_json(nlohmann::json& j, const AccessType& o);
    friend void from_json(const nlohmann::json& j, AccessType& o);
protected:
    AccessType::eAccessType m_value = AccessType::eAccessType::INVALID_VALUE_OPENAPI_GENERATED;
};

} // namespace org::openapitools::server::model

#endif /* AccessType_H_ */
