/**
* NRF NFManagement Service
* NRF NFManagement Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.2.0-alpha.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * AnNodeType.h
 *
 * Access Network Node Type (gNB, ng-eNB...)
 */

#ifndef AnNodeType_H_
#define AnNodeType_H_


#include "AnNodeType_anyOf.h"
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// Access Network Node Type (gNB, ng-eNB...)
/// </summary>
class  AnNodeType
{
public:
    AnNodeType();
    virtual ~AnNodeType() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const AnNodeType& rhs) const;
    bool operator!=(const AnNodeType& rhs) const;

    /////////////////////////////////////////////
    /// AnNodeType members


    AnNodeType_anyOf getValue() const;
    void setValue(AnNodeType_anyOf value);
    AnNodeType_anyOf::eAnNodeType_anyOf getEnumValue() const;
    void setEnumValue(AnNodeType_anyOf::eAnNodeType_anyOf value);
    friend void to_json(nlohmann::json& j, const AnNodeType& o);
    friend void from_json(const nlohmann::json& j, AnNodeType& o);
    friend void to_json(nlohmann::json& j, const AnNodeType_anyOf& o);
    friend void from_json(const nlohmann::json& j, AnNodeType_anyOf& o);
protected:
    AnNodeType_anyOf m_value;
};

} // namespace org::openapitools::server::model

#endif /* AnNodeType_H_ */
