/**
* NRF NFManagement Service
* NRF NFManagement Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.2.0-alpha.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * DataSetId_anyOf.h
 *
 * 
 */

#ifndef DataSetId_anyOf_H_
#define DataSetId_anyOf_H_


#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  DataSetId_anyOf
{
public:
    DataSetId_anyOf();
    virtual ~DataSetId_anyOf() = default;

    enum class eDataSetId_anyOf {
    // To have a valid default value.
    // Avoiding name clashes with user defined
    // enum values
    INVALID_VALUE_OPENAPI_GENERATED = 0,
    SUBSCRIPTION, 
    POLICY, 
    EXPOSURE, 
    APPLICATION
    };

    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const DataSetId_anyOf& rhs) const;
    bool operator!=(const DataSetId_anyOf& rhs) const;

    /////////////////////////////////////////////
    /// DataSetId_anyOf members

    DataSetId_anyOf::eDataSetId_anyOf getValue() const;
    void setValue(DataSetId_anyOf::eDataSetId_anyOf value);
    
    friend void to_json(nlohmann::json& j, const DataSetId_anyOf& o);
    friend void from_json(const nlohmann::json& j, DataSetId_anyOf& o);
protected:
    DataSetId_anyOf::eDataSetId_anyOf m_value = DataSetId_anyOf::eDataSetId_anyOf::INVALID_VALUE_OPENAPI_GENERATED;
};

} // namespace org::openapitools::server::model

#endif /* DataSetId_anyOf_H_ */
