/**
* NRF NFManagement Service
* NRF NFManagement Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.2.0-alpha.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * DccfInfo.h
 *
 * Information of a DCCF NF Instance
 */

#ifndef DccfInfo_H_
#define DccfInfo_H_


#include "NFType.h"
#include "Tai.h"
#include <string>
#include "TaiRange.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// Information of a DCCF NF Instance
/// </summary>
class  DccfInfo
{
public:
    DccfInfo();
    virtual ~DccfInfo() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const DccfInfo& rhs) const;
    bool operator!=(const DccfInfo& rhs) const;

    /////////////////////////////////////////////
    /// DccfInfo members

    /// <summary>
    /// 
    /// </summary>
    std::vector<NFType> getServingNfTypeList() const;
    void setServingNfTypeList(std::vector<NFType> const& value);
    bool servingNfTypeListIsSet() const;
    void unsetServingNfTypeList();
    /// <summary>
    /// 
    /// </summary>
    std::vector<std::string> getServingNfSetIdList() const;
    void setServingNfSetIdList(std::vector<std::string> const& value);
    bool servingNfSetIdListIsSet() const;
    void unsetServingNfSetIdList();
    /// <summary>
    /// 
    /// </summary>
    std::vector<Tai> getTaiList() const;
    void setTaiList(std::vector<Tai> const& value);
    bool taiListIsSet() const;
    void unsetTaiList();
    /// <summary>
    /// 
    /// </summary>
    std::vector<TaiRange> getTaiRangeList() const;
    void setTaiRangeList(std::vector<TaiRange> const& value);
    bool taiRangeListIsSet() const;
    void unsetTaiRangeList();

    friend void to_json(nlohmann::json& j, const DccfInfo& o);
    friend void from_json(const nlohmann::json& j, DccfInfo& o);
protected:
    std::vector<NFType> m_ServingNfTypeList;
    bool m_ServingNfTypeListIsSet;
    std::vector<std::string> m_ServingNfSetIdList;
    bool m_ServingNfSetIdListIsSet;
    std::vector<Tai> m_TaiList;
    bool m_TaiListIsSet;
    std::vector<TaiRange> m_TaiRangeList;
    bool m_TaiRangeListIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* DccfInfo_H_ */
