/**
* NRF NFManagement Service
* NRF NFManagement Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.2.0-alpha.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * GuamiListCond.h
 *
 * Subscription to a set of AMFs, based on their GUAMIs
 */

#ifndef GuamiListCond_H_
#define GuamiListCond_H_


#include <vector>
#include "Guami.h"
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// Subscription to a set of AMFs, based on their GUAMIs
/// </summary>
class  GuamiListCond
{
public:
    GuamiListCond();
    virtual ~GuamiListCond() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const GuamiListCond& rhs) const;
    bool operator!=(const GuamiListCond& rhs) const;

    /////////////////////////////////////////////
    /// GuamiListCond members

    /// <summary>
    /// 
    /// </summary>
    std::vector<Guami> getGuamiList() const;
    void setGuamiList(std::vector<Guami> const& value);

    friend void to_json(nlohmann::json& j, const GuamiListCond& o);
    friend void from_json(const nlohmann::json& j, GuamiListCond& o);
protected:
    std::vector<Guami> m_GuamiList;

    
};

} // namespace org::openapitools::server::model

#endif /* GuamiListCond_H_ */
