/**
* NRF NFManagement Service
* NRF NFManagement Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.2.0-alpha.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Ipv6PrefixRange.h
 *
 * Range of IPv6 prefixes
 */

#ifndef Ipv6PrefixRange_H_
#define Ipv6PrefixRange_H_


#include "Ipv6Prefix.h"
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// Range of IPv6 prefixes
/// </summary>
class  Ipv6PrefixRange
{
public:
    Ipv6PrefixRange();
    virtual ~Ipv6PrefixRange() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const Ipv6PrefixRange& rhs) const;
    bool operator!=(const Ipv6PrefixRange& rhs) const;

    /////////////////////////////////////////////
    /// Ipv6PrefixRange members

    /// <summary>
    /// 
    /// </summary>
    Ipv6Prefix getStart() const;
    void setStart(Ipv6Prefix const& value);
    bool startIsSet() const;
    void unsetStart();
    /// <summary>
    /// 
    /// </summary>
    Ipv6Prefix getEnd() const;
    void setEnd(Ipv6Prefix const& value);
    bool endIsSet() const;
    void unsetEnd();

    friend void to_json(nlohmann::json& j, const Ipv6PrefixRange& o);
    friend void from_json(const nlohmann::json& j, Ipv6PrefixRange& o);
protected:
    Ipv6Prefix m_Start;
    bool m_StartIsSet;
    Ipv6Prefix m_End;
    bool m_EndIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* Ipv6PrefixRange_H_ */
