/**
* NRF NFManagement Service
* NRF NFManagement Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.2.0-alpha.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * N1MessageClass.h
 *
 * Enumeration for N1 Message Class
 */

#ifndef N1MessageClass_H_
#define N1MessageClass_H_


#include "N1MessageClass_anyOf.h"
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// Enumeration for N1 Message Class
/// </summary>
class  N1MessageClass
{
public:
    N1MessageClass();
    virtual ~N1MessageClass() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const N1MessageClass& rhs) const;
    bool operator!=(const N1MessageClass& rhs) const;

    /////////////////////////////////////////////
    /// N1MessageClass members


    N1MessageClass_anyOf getValue() const;
    void setValue(N1MessageClass_anyOf value);
    N1MessageClass_anyOf::eN1MessageClass_anyOf getEnumValue() const;
    void setEnumValue(N1MessageClass_anyOf::eN1MessageClass_anyOf value);
    friend void to_json(nlohmann::json& j, const N1MessageClass& o);
    friend void from_json(const nlohmann::json& j, N1MessageClass& o);
    friend void to_json(nlohmann::json& j, const N1MessageClass_anyOf& o);
    friend void from_json(const nlohmann::json& j, N1MessageClass_anyOf& o);
protected:
    N1MessageClass_anyOf m_value;
};

} // namespace org::openapitools::server::model

#endif /* N1MessageClass_H_ */
