/**
* NRF NFManagement Service
* NRF NFManagement Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.2.0-alpha.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * NfInstanceIdListCond.h
 *
 * Subscription to a list of NF Instances
 */

#ifndef NfInstanceIdListCond_H_
#define NfInstanceIdListCond_H_


#include <string>
#include <vector>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// Subscription to a list of NF Instances
/// </summary>
class  NfInstanceIdListCond
{
public:
    NfInstanceIdListCond();
    virtual ~NfInstanceIdListCond() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const NfInstanceIdListCond& rhs) const;
    bool operator!=(const NfInstanceIdListCond& rhs) const;

    /////////////////////////////////////////////
    /// NfInstanceIdListCond members

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::string> getNfInstanceIdList() const;
    void setNfInstanceIdList(std::vector<std::string> const& value);

    friend void to_json(nlohmann::json& j, const NfInstanceIdListCond& o);
    friend void from_json(const nlohmann::json& j, NfInstanceIdListCond& o);
protected:
    std::vector<std::string> m_NfInstanceIdList;

    
};

} // namespace org::openapitools::server::model

#endif /* NfInstanceIdListCond_H_ */
