/**
* NRF NFManagement Service
* NRF NFManagement Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.2.0-alpha.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * NFServiceStatus.h
 *
 * Status of a given NF Service Instance of an NF Instance stored in NRF
 */

#ifndef NFServiceStatus_H_
#define NFServiceStatus_H_


#include "NFStatus_anyOf.h"
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// Status of a given NF Service Instance of an NF Instance stored in NRF
/// </summary>
class  NFServiceStatus
{
public:
    NFServiceStatus();
    virtual ~NFServiceStatus() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const NFServiceStatus& rhs) const;
    bool operator!=(const NFServiceStatus& rhs) const;

    /////////////////////////////////////////////
    /// NFServiceStatus members


    NFStatus_anyOf getValue() const;
    void setValue(NFStatus_anyOf value);
    NFStatus_anyOf::eNFStatus_anyOf getEnumValue() const;
    void setEnumValue(NFStatus_anyOf::eNFStatus_anyOf value);
    friend void to_json(nlohmann::json& j, const NFServiceStatus& o);
    friend void from_json(const nlohmann::json& j, NFServiceStatus& o);
    friend void to_json(nlohmann::json& j, const NFStatus_anyOf& o);
    friend void from_json(const nlohmann::json& j, NFStatus_anyOf& o);
protected:
    NFStatus_anyOf m_value;
};

} // namespace org::openapitools::server::model

#endif /* NFServiceStatus_H_ */
