/**
* NRF NFManagement Service
* NRF NFManagement Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.2.0-alpha.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "NfSetCond.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

NfSetCond::NfSetCond()
{
    m_NfSetId = "";
    
}

void NfSetCond::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool NfSetCond::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool NfSetCond::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "NfSetCond" : pathPrefix;

        
    return success;
}

bool NfSetCond::operator==(const NfSetCond& rhs) const
{
    return
    
    
    (getNfSetId() == rhs.getNfSetId())
    
    
    ;
}

bool NfSetCond::operator!=(const NfSetCond& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const NfSetCond& o)
{
    j = nlohmann::json();
    j["nfSetId"] = o.m_NfSetId;
    
}

void from_json(const nlohmann::json& j, NfSetCond& o)
{
    j.at("nfSetId").get_to(o.m_NfSetId);
    
}

std::string NfSetCond::getNfSetId() const
{
    return m_NfSetId;
}
void NfSetCond::setNfSetId(std::string const& value)
{
    m_NfSetId = value;
}


} // namespace org::openapitools::server::model

