/**
* NRF NFManagement Service
* NRF NFManagement Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.2.0-alpha.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * NwdafCapability.h
 *
 * Indicates the capability supported by the NWDAF
 */

#ifndef NwdafCapability_H_
#define NwdafCapability_H_


#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// Indicates the capability supported by the NWDAF
/// </summary>
class  NwdafCapability
{
public:
    NwdafCapability();
    virtual ~NwdafCapability() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const NwdafCapability& rhs) const;
    bool operator!=(const NwdafCapability& rhs) const;

    /////////////////////////////////////////////
    /// NwdafCapability members

    /// <summary>
    /// 
    /// </summary>
    bool isAnalyticsAggregation() const;
    void setAnalyticsAggregation(bool const value);
    bool analyticsAggregationIsSet() const;
    void unsetAnalyticsAggregation();
    /// <summary>
    /// 
    /// </summary>
    bool isAnalyticsMetadataProvisioning() const;
    void setAnalyticsMetadataProvisioning(bool const value);
    bool analyticsMetadataProvisioningIsSet() const;
    void unsetAnalyticsMetadataProvisioning();

    friend void to_json(nlohmann::json& j, const NwdafCapability& o);
    friend void from_json(const nlohmann::json& j, NwdafCapability& o);
protected:
    bool m_AnalyticsAggregation;
    bool m_AnalyticsAggregationIsSet;
    bool m_AnalyticsMetadataProvisioning;
    bool m_AnalyticsMetadataProvisioningIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* NwdafCapability_H_ */
