/**
* NRF NFManagement Service
* NRF NFManagement Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.2.0-alpha.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * PduSessionType.h
 *
 * PduSessionType indicates the type of a PDU session. It shall comply with the provisions defined in table 5.4.3.3-1.
 */

#ifndef PduSessionType_H_
#define PduSessionType_H_


#include "PduSessionType_anyOf.h"
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// PduSessionType indicates the type of a PDU session. It shall comply with the provisions defined in table 5.4.3.3-1.
/// </summary>
class  PduSessionType
{
public:
    PduSessionType();
    virtual ~PduSessionType() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const PduSessionType& rhs) const;
    bool operator!=(const PduSessionType& rhs) const;

    /////////////////////////////////////////////
    /// PduSessionType members


    PduSessionType_anyOf getValue() const;
    void setValue(PduSessionType_anyOf value);
    PduSessionType_anyOf::ePduSessionType_anyOf getEnumValue() const;
    void setEnumValue(PduSessionType_anyOf::ePduSessionType_anyOf value);
    friend void to_json(nlohmann::json& j, const PduSessionType& o);
    friend void from_json(const nlohmann::json& j, PduSessionType& o);
    friend void to_json(nlohmann::json& j, const PduSessionType_anyOf& o);
    friend void from_json(const nlohmann::json& j, PduSessionType_anyOf& o);
protected:
    PduSessionType_anyOf m_value;
};

} // namespace org::openapitools::server::model

#endif /* PduSessionType_H_ */
