/**
* NRF NFManagement Service
* NRF NFManagement Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.2.0-alpha.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "ServiceName.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

ServiceName::ServiceName()
{
    
}

void ServiceName::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool ServiceName::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool ServiceName::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "ServiceName" : pathPrefix;

    
    if (!m_value.validate(msg))
    {
        success = false;
    }
    return success;
}

bool ServiceName::operator==(const ServiceName& rhs) const
{
    return
    
    getValue() == rhs.getValue()
    ;
}

bool ServiceName::operator!=(const ServiceName& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const ServiceName& o)
{
    j = nlohmann::json();
    to_json(j, o.m_value);
}

void from_json(const nlohmann::json& j, ServiceName& o)
{
    from_json(j, o.m_value);
}

ServiceName_anyOf ServiceName::getValue() const
{
    return m_value;
}

void ServiceName::setValue(ServiceName_anyOf value)
{
    m_value = value;
}

ServiceName_anyOf::eServiceName_anyOf ServiceName::getEnumValue() const
{
    return m_value.getValue();
}

void ServiceName::setEnumValue(ServiceName_anyOf::eServiceName_anyOf  value)
{
    m_value.setValue(value);
}

} // namespace org::openapitools::server::model

