/**
* NRF NFManagement Service
* NRF NFManagement Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.2.0-alpha.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * TrustAfInfo.h
 *
 * Information of a trusted AF Instance
 */

#ifndef TrustAfInfo_H_
#define TrustAfInfo_H_


#include <string>
#include "AfEvent.h"
#include "SnssaiInfoItem.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// Information of a trusted AF Instance
/// </summary>
class  TrustAfInfo
{
public:
    TrustAfInfo();
    virtual ~TrustAfInfo() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const TrustAfInfo& rhs) const;
    bool operator!=(const TrustAfInfo& rhs) const;

    /////////////////////////////////////////////
    /// TrustAfInfo members

    /// <summary>
    /// 
    /// </summary>
    std::vector<SnssaiInfoItem> getSNssaiInfoList() const;
    void setSNssaiInfoList(std::vector<SnssaiInfoItem> const& value);
    bool sNssaiInfoListIsSet() const;
    void unsetSNssaiInfoList();
    /// <summary>
    /// 
    /// </summary>
    std::vector<AfEvent> getAfEvents() const;
    void setAfEvents(std::vector<AfEvent> const& value);
    bool afEventsIsSet() const;
    void unsetAfEvents();
    /// <summary>
    /// 
    /// </summary>
    std::vector<std::string> getAppIds() const;
    void setAppIds(std::vector<std::string> const& value);
    bool appIdsIsSet() const;
    void unsetAppIds();
    /// <summary>
    /// 
    /// </summary>
    std::vector<std::string> getInternalGroupId() const;
    void setInternalGroupId(std::vector<std::string> const& value);
    bool internalGroupIdIsSet() const;
    void unsetInternalGroupId();

    friend void to_json(nlohmann::json& j, const TrustAfInfo& o);
    friend void from_json(const nlohmann::json& j, TrustAfInfo& o);
protected:
    std::vector<SnssaiInfoItem> m_SNssaiInfoList;
    bool m_SNssaiInfoListIsSet;
    std::vector<AfEvent> m_AfEvents;
    bool m_AfEventsIsSet;
    std::vector<std::string> m_AppIds;
    bool m_AppIdsIsSet;
    std::vector<std::string> m_InternalGroupId;
    bool m_InternalGroupIdIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* TrustAfInfo_H_ */
