/**
* NRF NFManagement Service
* NRF NFManagement Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.2.0-alpha.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * UdrInfo.h
 *
 * Information of an UDR NF Instance
 */

#ifndef UdrInfo_H_
#define UdrInfo_H_


#include "IdentityRange.h"
#include "SupiRange.h"
#include <string>
#include "DataSetId.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// Information of an UDR NF Instance
/// </summary>
class  UdrInfo
{
public:
    UdrInfo();
    virtual ~UdrInfo() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const UdrInfo& rhs) const;
    bool operator!=(const UdrInfo& rhs) const;

    /////////////////////////////////////////////
    /// UdrInfo members

    /// <summary>
    /// Identifier of a group of NFs.
    /// </summary>
    std::string getGroupId() const;
    void setGroupId(std::string const& value);
    bool groupIdIsSet() const;
    void unsetGroupId();
    /// <summary>
    /// 
    /// </summary>
    std::vector<SupiRange> getSupiRanges() const;
    void setSupiRanges(std::vector<SupiRange> const& value);
    bool supiRangesIsSet() const;
    void unsetSupiRanges();
    /// <summary>
    /// 
    /// </summary>
    std::vector<IdentityRange> getGpsiRanges() const;
    void setGpsiRanges(std::vector<IdentityRange> const& value);
    bool gpsiRangesIsSet() const;
    void unsetGpsiRanges();
    /// <summary>
    /// 
    /// </summary>
    std::vector<IdentityRange> getExternalGroupIdentifiersRanges() const;
    void setExternalGroupIdentifiersRanges(std::vector<IdentityRange> const& value);
    bool externalGroupIdentifiersRangesIsSet() const;
    void unsetExternalGroupIdentifiersRanges();
    /// <summary>
    /// 
    /// </summary>
    std::vector<DataSetId> getSupportedDataSets() const;
    void setSupportedDataSets(std::vector<DataSetId> const& value);
    bool supportedDataSetsIsSet() const;
    void unsetSupportedDataSets();

    friend void to_json(nlohmann::json& j, const UdrInfo& o);
    friend void from_json(const nlohmann::json& j, UdrInfo& o);
protected:
    std::string m_GroupId;
    bool m_GroupIdIsSet;
    std::vector<SupiRange> m_SupiRanges;
    bool m_SupiRangesIsSet;
    std::vector<IdentityRange> m_GpsiRanges;
    bool m_GpsiRangesIsSet;
    std::vector<IdentityRange> m_ExternalGroupIdentifiersRanges;
    bool m_ExternalGroupIdentifiersRangesIsSet;
    std::vector<DataSetId> m_SupportedDataSets;
    bool m_SupportedDataSetsIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* UdrInfo_H_ */
