/**
* NRF NFManagement Service
* NRF NFManagement Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.2.0-alpha.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "UpfCond.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

UpfCond::UpfCond()
{
    m_ConditionType = "";
    m_SmfServingAreaIsSet = false;
    m_TaiListIsSet = false;
    
}

void UpfCond::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool UpfCond::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool UpfCond::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "UpfCond" : pathPrefix;

             
    if (smfServingAreaIsSet())
    {
        const std::vector<std::string>& value = m_SmfServingArea;
        const std::string currentValuePath = _pathPrefix + ".smfServingArea";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const std::string& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        
 
                i++;
            }
        }

    }
         
    if (taiListIsSet())
    {
        const std::vector<Tai>& value = m_TaiList;
        const std::string currentValuePath = _pathPrefix + ".taiList";
                
        
        if (value.size() < 1)
        {
            success = false;
            msg << currentValuePath << ": must have at least 1 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const Tai& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".taiList") && success;
 
                i++;
            }
        }

    }
    
    return success;
}

bool UpfCond::operator==(const UpfCond& rhs) const
{
    return
    
    
    (getConditionType() == rhs.getConditionType())
     &&
    
    
    ((!smfServingAreaIsSet() && !rhs.smfServingAreaIsSet()) || (smfServingAreaIsSet() && rhs.smfServingAreaIsSet() && getSmfServingArea() == rhs.getSmfServingArea())) &&
    
    
    ((!taiListIsSet() && !rhs.taiListIsSet()) || (taiListIsSet() && rhs.taiListIsSet() && getTaiList() == rhs.getTaiList()))
    
    ;
}

bool UpfCond::operator!=(const UpfCond& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const UpfCond& o)
{
    j = nlohmann::json();
    j["conditionType"] = o.m_ConditionType;
    if(o.smfServingAreaIsSet() || !o.m_SmfServingArea.empty())
        j["smfServingArea"] = o.m_SmfServingArea;
    if(o.taiListIsSet() || !o.m_TaiList.empty())
        j["taiList"] = o.m_TaiList;
    
}

void from_json(const nlohmann::json& j, UpfCond& o)
{
    j.at("conditionType").get_to(o.m_ConditionType);
    if(j.find("smfServingArea") != j.end())
    {
        j.at("smfServingArea").get_to(o.m_SmfServingArea);
        o.m_SmfServingAreaIsSet = true;
    } 
    if(j.find("taiList") != j.end())
    {
        j.at("taiList").get_to(o.m_TaiList);
        o.m_TaiListIsSet = true;
    } 
    
}

std::string UpfCond::getConditionType() const
{
    return m_ConditionType;
}
void UpfCond::setConditionType(std::string const& value)
{
    m_ConditionType = value;
}
std::vector<std::string> UpfCond::getSmfServingArea() const
{
    return m_SmfServingArea;
}
void UpfCond::setSmfServingArea(std::vector<std::string> const& value)
{
    m_SmfServingArea = value;
    m_SmfServingAreaIsSet = true;
}
bool UpfCond::smfServingAreaIsSet() const
{
    return m_SmfServingAreaIsSet;
}
void UpfCond::unsetSmfServingArea()
{
    m_SmfServingAreaIsSet = false;
}
std::vector<Tai> UpfCond::getTaiList() const
{
    return m_TaiList;
}
void UpfCond::setTaiList(std::vector<Tai> const& value)
{
    m_TaiList = value;
    m_TaiListIsSet = true;
}
bool UpfCond::taiListIsSet() const
{
    return m_TaiListIsSet;
}
void UpfCond::unsetTaiList()
{
    m_TaiListIsSet = false;
}


} // namespace org::openapitools::server::model

