/**
* NRF NFManagement Service
* NRF NFManagement Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.2.0-alpha.5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * UpfCond.h
 *
 * Subscription to a set of NF Instances (UPFs), able to serve a certain service area (i.e. SMF serving area or TAI list)
 */

#ifndef UpfCond_H_
#define UpfCond_H_


#include "Tai.h"
#include <string>
#include <vector>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// Subscription to a set of NF Instances (UPFs), able to serve a certain service area (i.e. SMF serving area or TAI list)
/// </summary>
class  UpfCond
{
public:
    UpfCond();
    virtual ~UpfCond() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const UpfCond& rhs) const;
    bool operator!=(const UpfCond& rhs) const;

    /////////////////////////////////////////////
    /// UpfCond members

    /// <summary>
    /// 
    /// </summary>
    std::string getConditionType() const;
    void setConditionType(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<std::string> getSmfServingArea() const;
    void setSmfServingArea(std::vector<std::string> const& value);
    bool smfServingAreaIsSet() const;
    void unsetSmfServingArea();
    /// <summary>
    /// 
    /// </summary>
    std::vector<Tai> getTaiList() const;
    void setTaiList(std::vector<Tai> const& value);
    bool taiListIsSet() const;
    void unsetTaiList();

    friend void to_json(nlohmann::json& j, const UpfCond& o);
    friend void from_json(const nlohmann::json& j, UpfCond& o);
protected:
    std::string m_ConditionType;

    std::vector<std::string> m_SmfServingArea;
    bool m_SmfServingAreaIsSet;
    std::vector<Tai> m_TaiList;
    bool m_TaiListIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* UpfCond_H_ */
