/**
* XRF OAuth2 Token Introspection Request API
* XRF OAuth2 Authorization server, token introspection API 
*
* The version of the OpenAPI document: 1
* Contact: tolgaoa@vt.edu
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* RequestJWKSAccessApiImpl.h
*
* 
*/

#ifndef REQUEST_JWKS_ACCESS_API_IMPL_H_
#define REQUEST_JWKS_ACCESS_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <RequestJWKSAccessApi.h>

#include <pistache/optional.h>

#include "JWKSErr.h"
#include "JWKSKeyReq.h"
#include "JWKSKeyRsp.h"

#include <string>
#include <xrf_main.hpp>
#include <spdlog/spdlog.h>

namespace xrf::api
{

using namespace xrf::model;
using namespace xrf::app;

class RequestJWKSAccessApiImpl : public xrf::api::RequestJWKSAccessApi {
public:
    RequestJWKSAccessApiImpl(std::shared_ptr<Pistache::Rest::Router>& rtr, xrf_main* xrf_main_inst, std::string addr);
    ~RequestJWKSAccessApiImpl() {};

    void j_wks_req(const Pistache::Optional<std::string>& keyid, Pistache::Http::ResponseWriter &response);

private:
    xrf_main* m_xrf_main;
    std::string m_addr;

};

} // namespace xrf::api



#endif
