/**
* XRF OAuth2 xApp Discvoery API
* XRF OAuth2 Authorization server, xApp Discovery API 
*
* The version of the OpenAPI document: 1
* Contact: tolgaoa@vt.edu
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* XAppDiscoverInstancesApiImpl.h
*
* 
*/

#ifndef X_APP_DISCOVER_INSTANCES_API_IMPL_H_
#define X_APP_DISCOVER_INSTANCES_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <XAppDiscoverInstancesApi.h>

#include <pistache/optional.h>

#include "AnyType.h"
#include "XAppDiscErr.h"
#include "XAppService.h"
#include <string>

namespace org::openapitools::server::api
{

using namespace org::openapitools::server::model;

class XAppDiscoverInstancesApiImpl : public org::openapitools::server::api::XAppDiscoverInstancesApi {
public:
    explicit XAppDiscoverInstancesApiImpl(const std::shared_ptr<Pistache::Rest::Router>& rtr);
    ~XAppDiscoverInstancesApiImpl() override = default;

    void x_app_disc_inst(const Pistache::Optional<XAppService> &targetxAppService, const Pistache::Optional<XAppService> &reqestingxAppService, const Pistache::Optional<Pistache::Http::Header::Raw> &acceptEncoding, Pistache::Http::ResponseWriter &response);

};

} // namespace org::openapitools::server::api



#endif
