/**
* XRF OAuth2 xApp Discvoery API
* XRF OAuth2 Authorization server, xApp Discovery API 
*
* The version of the OpenAPI document: 1
* Contact: tolgaoa@vt.edu
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* XAppRegisterInstanceApiImpl.h
*
* 
*/

#ifndef X_APP_REGISTER_INSTANCE_API_IMPL_H_
#define X_APP_REGISTER_INSTANCE_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <XAppRegisterInstanceApi.h>

#include <pistache/optional.h>

#include "XAppDiscErr.h"
#include "XAppProfile.h"

namespace org::openapitools::server::api
{

using namespace org::openapitools::server::model;

class XAppRegisterInstanceApiImpl : public org::openapitools::server::api::XAppRegisterInstanceApi {
public:
    explicit XAppRegisterInstanceApiImpl(const std::shared_ptr<Pistache::Rest::Router>& rtr);
    ~XAppRegisterInstanceApiImpl() override = default;

    void registerx_app_instance(const XAppProfile &xAppInstanceId, const XAppProfile &xAppProfile, Pistache::Http::ResponseWriter &response);

};

} // namespace org::openapitools::server::api



#endif
