/**
* XRF OAuth2 xApp Discvoery API
* XRF OAuth2 Authorization server, xApp Discovery API 
*
* The version of the OpenAPI document: 1
* Contact: tolgaoa@vt.edu
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "XAppDeleteInstanceApiImpl.h"

namespace xrf {
namespace api {

using namespace xrf::model;

XAppDeleteInstanceApiImpl::XAppDeleteInstanceApiImpl(const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : XAppDeleteInstanceApi(rtr)
{
}

void XAppDeleteInstanceApiImpl::deletex_app_instance(const std::string &xAppInstanceId, Pistache::Http::ResponseWriter &response) {
    response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

}
}

