/**
* XRF OAuth2 Token Introspection Request API
* XRF OAuth2 Authorization server, token introspection API 
*
* The version of the OpenAPI document: 1
* Contact: tolgaoa@vt.edu
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * JWKSKeyReq.h
 *
 * Contains information related to the JWKS key request
 */

#ifndef JWKSKeyReq_H_
#define JWKSKeyReq_H_


#include <string>
#include <nlohmann/json.hpp>

namespace xrf::model
{

/// <summary>
/// Contains information related to the JWKS key request
/// </summary>
class  JWKSKeyReq
{
public:
    JWKSKeyReq();
    virtual ~JWKSKeyReq() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const JWKSKeyReq& rhs) const;
    bool operator!=(const JWKSKeyReq& rhs) const;

    /////////////////////////////////////////////
    /// JWKSKeyReq members

    /// <summary>
    /// key ID of the token up for validationz
    /// </summary>
    std::string getKeyid() const;
    void setKeyid(std::string const& value);

    friend void to_json(nlohmann::json& j, const JWKSKeyReq& o);
    friend void from_json(const nlohmann::json& j, JWKSKeyReq& o);
protected:
    std::string m_Keyid;

    
};

} // namespace xrf::model

#endif /* JWKSKeyReq_H_ */
