/**
* XRF OAuth2 xApp Discvoery API
* XRF OAuth2 Authorization server, xApp Discovery API 
*
* The version of the OpenAPI document: 1
* Contact: tolgaoa@vt.edu
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "XAppStatus.h"
#include "Helpers.h"

#include <sstream>

namespace xrf::model
{

XAppStatus::XAppStatus()
{
    
}

void XAppStatus::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw xrf::helpers::ValidationException(msg.str());
    }
}

bool XAppStatus::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool XAppStatus::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "XAppStatus" : pathPrefix;

    
    return success;
}

bool XAppStatus::operator==(const XAppStatus& rhs) const
{
    return true;
    
    
    ;
}

bool XAppStatus::operator!=(const XAppStatus& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const XAppStatus& o)
{
    j = nlohmann::json();
    
}

void from_json(const nlohmann::json& j, XAppStatus& o)
{
    
}



} // namespace xrf::model

