/**
* XRF OAuth2 xApp Discvoery API
* XRF OAuth2 Authorization server, xApp Discovery API 
*
* The version of the OpenAPI document: 1
* Contact: tolgaoa@vt.edu
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * XAppStatus.h
 *
 * xApp status identifier
 */

#ifndef XAppStatus_H_
#define XAppStatus_H_


#include "XAppStatus_anyOf.h"
#include <nlohmann/json.hpp>

namespace xrf::model
{

/// <summary>
/// xApp status identifier
/// </summary>
class  XAppStatus
{
public:
    XAppStatus();
    virtual ~XAppStatus() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const XAppStatus& rhs) const;
    bool operator!=(const XAppStatus& rhs) const;

    /////////////////////////////////////////////
    /// XAppStatus members


    friend void to_json(nlohmann::json& j, const XAppStatus& o);
    friend void from_json(const nlohmann::json& j, XAppStatus& o);
protected:
    
};

} // namespace xrf::model

#endif /* XAppStatus_H_ */
